[package]
name = "app_schedule"
version = "0.1.0"
edition = "2021"
authors = ["Anton Kolomeytsev <tonykolomeytsev@gmail.com>"]

[dependencies]
common_errors = { path = "../common_errors" }
domain_schedule_models = { path = "../domain_schedule_models" }
feature_schedule = { path = "../feature_schedule" }

serde = { version = "1.0", features = ["derive"] }
actix-web = { version = "4" }
anyhow = { version = "1.0" }
derive_more = { version = "0.99.17" }
