[workspace]
members = [
  "crates/app_schedule",
  "crates/common_database",
  "crates/common_errors",
  "crates/common_in_memory_cache",
  "crates/common_persistent_cache",
  "crates/domain_bot",
  "crates/domain_mobile",
  "crates/domain_schedule",
  "crates/domain_schedule_models",
  "crates/domain_schedule_shift",
  "crates/domain_telegram_bot",
  "crates/domain_vk_bot",
  "crates/feature_schedule",
  "crates/feature_telegram_bot",
  "crates/feature_vk_bot",
]

[profile.release]
opt-level = 3
lto = true
