[workspace]
members = [
  "app_schedule",
  "common_database",
  "common_errors",
  "common_in_memory_cache",
  "common_persistent_cache",
  "domain_schedule",
  "domain_schedule_models",
  "domain_schedule_shift",
  "feature_schedule",
]

[profile.release]
opt-level = 3
lto = true
