[workspace]
members = [
  "app_schedule",
  "common_database",
  "common_errors",
  "common_in_memory_cache",
  "common_persistent_cache",
  "domain_bot",
  "domain_mobile",
  "domain_schedule",
  "domain_schedule_models",
  "domain_schedule_shift",
  "domain_telegram_bot",
  "domain_vk_bot",
  "feature_schedule",
  "feature_telegram_bot",
  "feature_vk_bot",
]

[profile.release]
opt-level = 3
lto = true
