[package]
name = "rocket_hello"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "app_schedule",
    "common_in_memory_cache",
    "domain_schedule",
    "domain_schedule_models",
    "feature_schedule",
]

[dependencies]
domain_schedule_models = { path = "domain_schedule_models" }

serde = { version = "1.0", features = ["derive"] }
rocket = { version="0.5.0-rc.2", features=["json"] }
