[package]
name = "restix_macro"
version = "0.1.0"
edition = "2021"
authors = ["Anton Kolomeytsev <tonykolomeytsev@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
restix_impl = { path = "../impl" }

proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
