[package]
name = "common_database"
version = "0.1.0"
edition = "2021"
authors = ["Anton Kolomeytsev <tonykolomeytsev@gmail.com>"]

[dependencies]
common_rust = { workspace = true }

anyhow = { version = "1.0" }
deadpool-postgres = { version = "0.10", features = ["serde"] }
tokio-postgres = "0.7"
