[package]
name = "common_in_memory_cache"
version = "0.1.0"
edition = "2021"
authors = ["Anton Kolomeytsev <tonykolomeytsev@gmail.com>"]

[dependencies]
chrono = { workspace = true, features = ["serde"] }
lru = { workspace = true }
serde = { workspace = true, features = ["derive"] }
