[package]
name = "common_in_memory_cache"
version = "0.1.0"
edition = "2021"
authors = ["Anton Kolomeytsev <tonykolomeytsev@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
lru = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
