name: Deploy beta-version to DEV server

on:
  push:
    tags:
      - "beta/*"

jobs:
  deploy:
    name: Release Build
    runs-on: ubuntu-latest
    environment: "Deploy Environment"
    steps:
      - uses: actions/checkout@v3

      - name: Put release version from tag name to ENV
        run: |
          echo "RELEASE_VERSION='beta-${GITHUB_REF#refs/*/*/}'" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app_schedule
        uses: docker/build-push-action@v4
        with:
          file: "./app_schedule/Dockerfile"
          push: true
          tags: tonykolomeytsev/mpeix-backend-app-schedule:${{ env.RELEASE_VERSION }}

      - name: Build and push app_telegram_bot
        uses: docker/build-push-action@v4
        with:
          file: "./app_telegram_bot/Dockerfile"
          push: true
          tags: tonykolomeytsev/mpeix-backend-app-telegram-bot:${{ env.RELEASE_VERSION }}

      - name: Build and push app_vk_bot
        uses: docker/build-push-action@v4
        with:
          file: "./app_vk_bot/Dockerfile"
          push: true
          tags: tonykolomeytsev/mpeix-backend-app-vk-bot:beta-${{ env.RELEASE_VERSION }}
